### ISSUE TITLE
Replace classes by functions (sugestion)

### ISSUE THREAD

**Issue by mishelashala** [lambdabricks/bricks-front-react#7]
It works in the same way, you only have to return a React Element (or Component) from the function.
And because functions are object you can still define properties to it like `propTypes`.

``` javascript
...

const Pipe = function ({ inputPosition, fillColor, strokeColor, outputPosition, type }) {
  ...

  return (
    <Shape
       d={ path }
      fill={ fillColor }
      stroke={ strokeColor }
    />
  )
}

Pipe.propTypes = {
  ...
}
```

**Comment by pel-daniel** [comment]
I know about them ([stateless functions](https://facebook.github.io/react/docs/reusable-components.html#stateless-functions)), but just work for stateless components.

What would you think will be the advantage of doing this replaces ?

**Comment by mishelashala** [comment]
Classes obfuscate JavaScript behavior, I've been working with a large code base lately and its easier to reason about, and its more loyal to react's philosophy.
